name: my_stake
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  ###
  flutter_bloc: ^8.1.6
  go_router: ^14.2.0
  shared_preferences: ^2.2.3
  flutter_inappwebview: ^5.8.0
  flutter_svg: ^2.0.10+1
  firebase_messaging: ^14.2.2
  flutter_local_notifications: ^9.8.0+1
  firebase_analytics:
  cupertino_icons: ^1.0.6
  app_tracking_transparency: ^2.0.4
  hive_flutter: ^1.1.0
  share_plus: ^7.2.2
  appsflyer_sdk: 
  firebase_core: 
  intl: ^0.19.0
  firebase_remote_config:
  currency_picker: ^2.0.21
  fancy_shimmer_image: ^2.0.3
  overlay_support: ^2.1.0
  cached_network_image: ^3.3.1
  ###
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
  fonts:
    - family: SF
      fonts:
        - asset: assets/fonts/SFProText-Medium.ttf
    - family: SFBold
      fonts:
        - asset: assets/fonts/SFProText-Bold.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf